inherit_from: ../.rubocop.yml

require:
  - rubocop-rspec
  - rubocop-rspec_rails

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Max: 250

RSpec/AlignLeftLetBrace:
  Enabled: true

RSpec/ContextWording:
  Enabled: true
  Prefixes: [when, with, without, if, where, for, as, after, upon]

RSpec/ExpectActual:
  Enabled: true

RSpec/ExampleLength:
  Max: 10

RSpecRails/InferredSpecType:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: true

RSpec/MessageExpectation:
  Enabled: true

RSpec/NestedGroups:
  Enabled: true
  Max: 6
